version: "3.5"

volumes:
  jiu_data:

services: 
  jiu_db:
    image: postgres:13
    container_name: jiu_data
    volumes:
      - jiu_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jiu
    ports:
      - 5431:5432